AGAINTRdd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -74,14 +74,14 @@ jobs:   #here we specify the jobs - We could have multiple jobs
 #          flutter pub get
 #          flutter pub run change_app_package_name:main com.example.ci_cd
 
-#      - name: Check Directory Contents
-#        run: ls -R assets/icon
+      - name: Check Directory Contents
+        run: ls -R assets/icon
 
 #      - name: Set Permissions for Image File
 #        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"
 #
-#      - name: Set Permissions for Image File
-#        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
+      - name: Set Permissions for Image File
+        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
 
 #      - name: Update pubspec.yaml and change app icon
 #        run: |
@@ -110,20 +110,20 @@ jobs:   #here we specify the jobs - We could have multiple jobs
       
       
 
-#      - name: Update pubspec.yaml
-#        run: |
-#          sed -i 's|image_path:.*|image_path: "assets/icon/desk_icon.png"|' pubspec.yaml
-#          if ! grep -q 'image_path:' pubspec.yaml; then
-#            echo "flutter_icons section not found, adding..."
-#            echo "flutter_icons:" >> pubspec.yaml
-#            echo "  android: true" >> pubspec.yaml
-#            echo "  ios: true" >> pubspec.yaml
-#            echo '  image_path: "assets/icon/desk_icon.png"' >> pubspec.yaml
-#          else
-#            echo "flutter_icons section found, no changes needed."
-#          fi
-#          flutter pub get
-#          flutter pub run flutter_launcher_icons:main
+      - name: Update pubspec.yaml
+        run: |
+          sed -i 's|image_path:.*|image_path: "assets/icon/desk_icon.png"|' pubspec.yaml
+          if ! grep -q 'image_path:' pubspec.yaml; then
+            echo "flutter_icons section not found, adding..."
+            echo "flutter_icons:" >> pubspec.yaml
+            echo "  android: true" >> pubspec.yaml
+            echo "  ios: true" >> pubspec.yaml
+            echo '  image_path: "assets/icon/desk_icon.png"' >> pubspec.yaml
+          else
+            echo "flutter_icons section found, no changes needed."
+          fi
+          flutter pub get
+          flutter pub run flutter_launcher_icons:main
 
 #      - name: Build Android
 #        run: cd android && ./gradlew assembleDebug
