AGAINTRY

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,10 +40,10 @@ jobs:   #here we specify the jobs - We could have multiple jobs
           set +x
 
 
-#      - name: Change package name
-#        run: |
-#          flutter pub get
-#          flutter pub run change_app_package_name:main $CONFIG.packageName
+      - name: Change package name
+        run: |
+          flutter pub get
+          flutter pub run change_app_package_name:main --app_package_name=$CONFIG.packageName
 
 #      - name: Change package name
 #        run: |
@@ -53,27 +53,27 @@ jobs:   #here we specify the jobs - We could have multiple jobs
 #      - name: Check Directory Contents
 #        run: ls -R assets/icon
 
-#      - name: Set Permissions for Image File
-#        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"
-
       - name: Set Permissions for Image File
-        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
+        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"
 
-#      - name: Update pubspec.yaml
-#        run: |
-#          ICON_PATH="assets/icon/$(echo $CONFIG | jq -r .iconPath)"
-#          sed -i "s|image_path:.*|image_path: \"$ICON_PATH\"|" pubspec.yaml
-#          if ! grep -q 'image_path:' pubspec.yaml; then
-#             echo "flutter_icons section not found, adding..."
-#             echo "flutter_icons:" >> pubspec.yaml
-#             echo "  android: true" >> pubspec.yaml
-#             echo "  ios: true" >> pubspec.yaml
-#             echo "  image_path: \"$ICON_PATH\"" >> pubspec.yaml
-#          else
-#             echo "flutter_icons section found, no changes needed."
-#          fi
-#          flutter pub get
-#          flutter pub run flutter_launcher_icons:main
+#      - name: Set Permissions for Image File
+#        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
+
+      - name: Update pubspec.yaml
+        run: |
+          ICON_PATH="assets/icon/$(echo $CONFIG | jq -r .iconPath)"
+          sed -i "s|image_path:.*|image_path: \"$ICON_PATH\"|" pubspec.yaml
+          if ! grep -q 'image_path:' pubspec.yaml; then
+             echo "flutter_icons section not found, adding..."
+             echo "flutter_icons:" >> pubspec.yaml
+             echo "  android: true" >> pubspec.yaml
+             echo "  ios: true" >> pubspec.yaml
+             echo "  image_path: \"$ICON_PATH\"" >> pubspec.yaml
+          else
+             echo "flutter_icons section found, no changes needed."
+          fi
+          flutter pub get
+          flutter pub run flutter_launcher_icons:main
       
       
 
