AGAINTRdd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,26 +22,26 @@ jobs:   #here we specify the jobs - We could have multiple jobs
         with:
           channel: 'stable'
 
+#
+#      - name: Set Permissions for AndroidManifest.xml
+#        run: chmod +w android/app/src/main/AndroidManifest.xml
+#
+#      - name: Debug AndroidManifest.xml
+#        run: cat android/app/src/main/AndroidManifest.xml
 
-      - name: Set Permissions for AndroidManifest.xml
-        run: chmod +w android/app/src/main/AndroidManifest.xml
-
-      - name: Debug AndroidManifest.xml
-        run: cat android/app/src/main/AndroidManifest.xml
-
-      - name: Read Config File
-        id: read-config
-        run: echo "CONFIG=$(cat config.json | tr -d '\n')" >> $GITHUB_ENV
+#      - name: Read Config File
+#        id: read-config
+#        run: echo "CONFIG=$(cat config.json | tr -d '\n')" >> $GITHUB_ENV
 
 
-      - name: Change package name and app name
-        run: |
-          flutter pub get
-          flutter pub run change_app_package_name:main --app_package_name=$CONFIG.packageName
-
-          set -x
-          sed -i "s/android:label=\"ci_cd\"/android:label=\"$CONFIG.appName\"/" android/app/src/main/AndroidManifest.xml
-          set +x
+#      - name: Change package name and app name
+#        run: |
+#          flutter pub get
+#          flutter pub run change_app_package_name:main --app_package_name=$CONFIG.packageName
+#
+#          set -x
+#          sed -i "s/android:label=\"ci_cd\"/android:label=\"$CONFIG.appName\"/" android/app/src/main/AndroidManifest.xml
+#          set +x
       
       
       
@@ -73,11 +73,11 @@ jobs:   #here we specify the jobs - We could have multiple jobs
 #      - name: Check Directory Contents
 #        run: ls -R assets/icon
 
-      - name: Set Permissions for Image File
-        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"
-
-      - name: Set Permissions for Image File
-        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
+#      - name: Set Permissions for Image File
+#        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"
+#
+#      - name: Set Permissions for Image File
+#        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
 
 #      - name: Update pubspec.yaml and change app icon
 #        run: |
@@ -88,21 +88,21 @@ jobs:   #here we specify the jobs - We could have multiple jobs
 #          flutter pub run flutter_launcher_icons:main --config=flutter_launcher_icons.yaml
 
 
-      - name: Update pubspec.yaml
-        run: |
-          ICON_PATH="assets/icon/$(echo $CONFIG | jq -r .iconPath)"
-          sed -i "s|image_path:.*|image_path: \"$ICON_PATH\"|" pubspec.yaml
-          if ! grep -q 'image_path:' pubspec.yaml; then
-             echo "flutter_icons section not found, adding..."
-             echo "flutter_icons:" >> pubspec.yaml
-             echo "  android: true" >> pubspec.yaml
-             echo "  ios: true" >> pubspec.yaml
-             echo "  image_path: \"$ICON_PATH\"" >> pubspec.yaml
-          else
-             echo "flutter_icons section found, no changes needed."
-          fi
-          flutter pub get
-          flutter pub run flutter_launcher_icons:main
+#      - name: Update pubspec.yaml
+#        run: |
+#          ICON_PATH="assets/icon/$(echo $CONFIG | jq -r .iconPath)"
+#          sed -i "s|image_path:.*|image_path: \"$ICON_PATH\"|" pubspec.yaml
+#          if ! grep -q 'image_path:' pubspec.yaml; then
+#             echo "flutter_icons section not found, adding..."
+#             echo "flutter_icons:" >> pubspec.yaml
+#             echo "  android: true" >> pubspec.yaml
+#             echo "  ios: true" >> pubspec.yaml
+#             echo "  image_path: \"$ICON_PATH\"" >> pubspec.yaml
+#          else
+#             echo "flutter_icons section found, no changes needed."
+#          fi
+#          flutter pub get
+#          flutter pub run flutter_launcher_icons:main
       
       
 
@@ -126,11 +126,11 @@ jobs:   #here we specify the jobs - We could have multiple jobs
 #        working-directory: ./android
 
 
-      - name: Debug Modified AndroidManifest.xml
-        run: cat android/app/src/main/AndroidManifest.xml
+#      - name: Debug Modified AndroidManifest.xml
+#        run: cat android/app/src/main/AndroidManifest.xml
 
-      - name: Clean Build
-        run: flutter clean
+#      - name: Clean Build
+#        run: flutter clean
 
       - name: Build Gradle
         run: flutter build apk --debug
