added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,23 +27,23 @@ jobs:   #here we specify the jobs - We could have multiple jobs
         run: echo "CONFIG=$(cat config.json | tr -d '\n')" >> $GITHUB_ENV
 
 
-#      - name: Change app name
-#        run: |
-#          set -x
-#          sed -i "s/android:label=\"ci_cd\"/android:label=\"$CONFIG.appName\"/" android/app/src/main/AndroidManifest.xml
-#          set +x
-
       - name: Change app name
         run: |
           set -x
-          sed -i 's/android:label="ci_cd"/android:label=$CONFIG.appName/' android/app/src/main/AndroidManifest.xml
+          sed -i "s/android:label=\"ci_cd\"/android:label=\"$CONFIG.appName\"/" android/app/src/main/AndroidManifest.xml
           set +x
 
-
-#      - name: Change package name
+#      - name: Change app name
 #        run: |
-#          flutter pub get
-#          flutter pub run change_app_package_name:main $CONFIG.packageName
+#          set -x
+#          sed -i 's/android:label="ci_cd"/android:label=$CONFIG.appName/' android/app/src/main/AndroidManifest.xml
+#          set +x
+
+
+      - name: Change package name
+        run: |
+          flutter pub get
+          flutter pub run change_app_package_name:main $CONFIG.packageName
 
 #      - name: Change package name
 #        run: |
@@ -53,11 +53,11 @@ jobs:   #here we specify the jobs - We could have multiple jobs
 #      - name: Check Directory Contents
 #        run: ls -R assets/icon
 
-      - name: Set Permissions for Image File
-        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"
+#      - name: Set Permissions for Image File
+#        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"
 
-        #      - name: Set Permissions for Image File
-#        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
+      - name: Set Permissions for Image File
+        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
 
 #      - name: Update pubspec.yaml
 #        run: |
@@ -77,20 +77,20 @@ jobs:   #here we specify the jobs - We could have multiple jobs
       
       
 
-      #      - name: Update pubspec.yaml
-#        run: |
-#          sed -i 's|image_path:.*|image_path: "assets/icon/desk_icon.png"|' pubspec.yaml
-#          if ! grep -q 'image_path:' pubspec.yaml; then
-#            echo "flutter_icons section not found, adding..."
-#            echo "flutter_icons:" >> pubspec.yaml
-#            echo "  android: true" >> pubspec.yaml
-#            echo "  ios: true" >> pubspec.yaml
-#            echo '  image_path: "assets/icon/desk_icon.png"' >> pubspec.yaml
-#          else
-#            echo "flutter_icons section found, no changes needed."
-#          fi
-#          flutter pub get
-#          flutter pub run flutter_launcher_icons:main
+      - name: Update pubspec.yaml
+        run: |
+          sed -i 's|image_path:.*|image_path: "assets/icon/desk_icon.png"|' pubspec.yaml
+          if ! grep -q 'image_path:' pubspec.yaml; then
+            echo "flutter_icons section not found, adding..."
+            echo "flutter_icons:" >> pubspec.yaml
+            echo "  android: true" >> pubspec.yaml
+            echo "  ios: true" >> pubspec.yaml
+            echo '  image_path: "assets/icon/desk_icon.png"' >> pubspec.yaml
+          else
+            echo "flutter_icons section found, no changes needed."
+          fi
+          flutter pub get
+          flutter pub run flutter_launcher_icons:main
 
 #      - name: Build Android
 #        run: cd android && ./gradlew assembleDebug
