added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -80,15 +80,15 @@ jobs:   #here we specify the jobs - We could have multiple jobs
       - name: Update pubspec.yaml
         run: |
           sed -i 's|image_path:.*|image_path: "assets/icon/desk_icon.png"|' pubspec.yaml
-          if ! grep -q 'image_path:' pubspec.yaml; then
-            echo "flutter_icons section not found, adding..."
-            echo "flutter_icons:" >> pubspec.yaml
-            echo "  android: true" >> pubspec.yaml
-            echo "  ios: true" >> pubspec.yaml
-            echo '  image_path: "assets/icon/desk_icon.png"' >> pubspec.yaml
-          else
-            echo "flutter_icons section found, no changes needed."
-          fi
+#          if ! grep -q 'image_path:' pubspec.yaml; then
+#            echo "flutter_icons section not found, adding..."
+#            echo "flutter_icons:" >> pubspec.yaml
+#            echo "  android: true" >> pubspec.yaml
+#            echo "  ios: true" >> pubspec.yaml
+#            echo '  image_path: "assets/icon/desk_icon.png"' >> pubspec.yaml
+#          else
+#            echo "flutter_icons section found, no changes needed."
+#          fi
           flutter pub get
           flutter pub run flutter_launcher_icons:main
 
