added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,8 +41,8 @@ jobs:   #here we specify the jobs - We could have multiple jobs
       - name: Change app name
         run: |
           set -x
-          NAME=$(jq -r '.appName' config.json)
-          sed -i "s/android:label=\"ci_cd\"/android:label=\"$NAME\"/" android/app/src/main/AndroidManifest.xml
+          APP_NAME=$(jq -r '.appName' config.json)
+          sed -i "s/android:label=\"ci_cd\"/android:label=\"$APP_NAME\"/" android/app/src/main/AndroidManifest.xml
           set +x
 
 #
@@ -63,59 +63,59 @@ jobs:   #here we specify the jobs - We could have multiple jobs
 
       - name: Change package name
         run: |
+          PACKAGE_NAME=$(jq -r '.packageName' config.json)
           flutter pub get
-          flutter pub run change_app_package_name:main com.example.ci_cd
+          flutter pub run change_app_package_name:main $PACKAGE_NAME
 
       - name: Check Directory Contents
         run: ls -R assets/icon
 
-#      - name: Set Permissions for Image File
-#        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"
-#
       - name: Set Permissions for Image File
-        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
+        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"
+#
+#      - name: Set Permissions for Image File
+#        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"
 
 #      - name: Update pubspec.yaml and change app icon
 #        run: |
 #          ICON_PATH="assets/icon/$(echo $CONFIG | jq -r .iconPath)"
 #          sed -i "s|image_path:.*|image_path: \"$ICON_PATH\"|" pubspec.yaml
-#
 #          flutter pub get
 #          flutter pub run flutter_launcher_icons:main --config=flutter_launcher_icons.yaml
 
 
-#      - name: Update pubspec.yaml
-#        run: |
-#          ICON_PATH="assets/icon/$(echo $CONFIG | jq -r .iconPath)"
-#          sed -i "s|image_path:.*|image_path: \"$ICON_PATH\"|" pubspec.yaml
-#          if ! grep -q 'image_path:' pubspec.yaml; then
-#             echo "flutter_icons section not found, adding..."
-#             echo "flutter_icons:" >> pubspec.yaml
-#             echo "  android: true" >> pubspec.yaml
-#             echo "  ios: true" >> pubspec.yaml
-#             echo "  image_path: \"$ICON_PATH\"" >> pubspec.yaml
-#          else
-#             echo "flutter_icons section found, no changes needed."
-#          fi
-#          flutter pub get
-#          flutter pub run flutter_launcher_icons:main
-
-
-
       - name: Update pubspec.yaml
         run: |
-          sed -i 's|image_path:.*|image_path: "assets/icon/desk_icon.png"|' pubspec.yaml
+          ICON_PATH="assets/icon/$(echo $CONFIG | jq -r .iconPath)"
+          sed -i "s|image_path:.*|image_path: \"$ICON_PATH\"|" pubspec.yaml
           if ! grep -q 'image_path:' pubspec.yaml; then
-            echo "flutter_icons section not found, adding..."
-            echo "flutter_icons:" >> pubspec.yaml
-            echo "  android: true" >> pubspec.yaml
-            echo "  ios: true" >> pubspec.yaml
-            echo '  image_path: "assets/icon/desk_icon.png"' >> pubspec.yaml
+             echo "flutter_icons section not found, adding..."
+             echo "flutter_icons:" >> pubspec.yaml
+             echo "  android: true" >> pubspec.yaml
+             echo "  ios: true" >> pubspec.yaml
+             echo "  image_path: \"$ICON_PATH\"" >> pubspec.yaml
           else
-            echo "flutter_icons section found, no changes needed."
+             echo "flutter_icons section found, no changes needed."
           fi
           flutter pub get
           flutter pub run flutter_launcher_icons:main
+
+
+
+#      - name: Update pubspec.yaml
+#        run: |
+#          sed -i 's|image_path:.*|image_path: "assets/icon/desk_icon.png"|' pubspec.yaml
+#          if ! grep -q 'image_path:' pubspec.yaml; then
+#            echo "flutter_icons section not found, adding..."
+#            echo "flutter_icons:" >> pubspec.yaml
+#            echo "  android: true" >> pubspec.yaml
+#            echo "  ios: true" >> pubspec.yaml
+#            echo '  image_path: "assets/icon/desk_icon.png"' >> pubspec.yaml
+#          else
+#            echo "flutter_icons section found, no changes needed."
+#          fi
+#          flutter pub get
+#          flutter pub run flutter_launcher_icons:main
 
 
       - name: Build Gradle
